---
deployment:
  tasks:
    - echo "Starting deployment"
    - export DEPLOYPATH=/home/d187bf5/my-react-app
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH/
    - echo "Files copied, starting npm install"
    - cd $DEPLOYPATH && npm install --production
    - echo "npm install completed"